### ISSUE TITLE
BluetoothClient causes NotImplementedException in version 4.0.28

### ISSUE THREAD

**Issue by snydesc** [inthehand/32feet#185]
`using (BluetoothClient client = new BluetoothClient())` throws the following exception in version 4.0.28 of InTheHand.Net.Bluetooth in a Xamarin Android Project.

"NotImplementedException  This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

Downgrading back to 4.0.27 resolves the issue.
I added 4.0.28 to the Android project  to see if that would fix the problem however the exception is still thrown.

**Comment by peterfoot** [comment]
What version of Android are you targeting in your csproj?

**Comment by snydesc** [comment]
#

> What version of mono Android are you targeting in your csproj?

Android 10 (API 29)

**Comment by peterfoot** [comment]
the library recently moved to building against monoandroid10.0 so if your project is set to monoandroid90 or earlier it will probably pull in the wrong (.NET Standard) dll from the NuGet package. I'm looking at adding both versions in for the next release because you may well have a project file with the older version depending on the vs version (for new templates) or when the project was originally created.

**Comment by peterfoot** [comment]
This should now be resolved in 4.0.29

**Comment by wagenheimer** [comment]
I also could not run the IOS RfcoomXamarinForms sample, it also fails with "NotImplementedException This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

**Comment by wagenheimer** [comment]
Only a detail, The RfcoomXamarinForms WPF sample works as expected.

**Comment by mdima** [comment]
Hello, 
 same here, working in iOS and using MAUI. 

When I run `client = new BluetoothClient();`
I receive the follwoing error: 

```
[0:] An error occurred: 'This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'. Callstack: '   at InTheHand.Net.Sockets.BluetoothClient.PlatformInitialize()
   at InTheHand.Net.Sockets.BluetoothClient..ctor()
```

Running the same code on an Android device everything works. 
InTheHand.Net.Bluetooth is versioned 4.0.31. 

Thanks for the support,
Michele

**Comment by kwon0408** [comment]
I have same problem on an Windows Console app, both on x64 and Any CPU. NuGet package version is 4.0.36.

**Comment by msschl** [comment]
Same for a standard console application:

Also `net7.0-windows`, `net8.0-windows` are not working as well
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.34" />
  </ItemGroup>

</Project>
```

**Comment by peterfoot** [comment]
I'm not sure what's going on there as your code is calling the BluetoothLE library and the error refers to the Bluetooth Classic library. Bluetooth LE requires Windows 10 or above so specifying a more general platform like net7.0-windows will step back to the next available dll which will be the .NET Standard one which is just a placeholder. Changing your project to e.g. net7.0-windows10.0.19041.0 should resolve this.

**Comment by msschl** [comment]
Nop, its also not working.
