### ISSUE TITLE
GattService.GetCharacteristicAsync(BluetoothUuid) on iOS causing System.NullReferenceException due to race condition

### ISSUE THREAD

**Issue by eechen-goldmine** [inthehand/32feet#238]
Platform: net6.0-ios
Lib: InTheHand.BluetoothLE 4.0.25, 4.0.26

To reproduce:
```
// Example getting battery level from a connected BLE device
var service = await bluetoothDevice.Gatt.GetPrimaryServiceAsync(BluetoothUuid.FromShortId(0x180f));
if (service != null) {
  // NullReferenceException raised in call to GetCharacteristicAsync().
  var characteristic = await service.GetCharacteristicAsync(BluetoothUuid.FromShortId(0x2a19));
}
```
The crash log shows:
```
2022-11-02 11:27:09.935 TestBLELibrary[698:215217] Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at InTheHand.Bluetooth.GattService.PlatformGetCharacteristic(BluetoothUuid characteristic) in C:\Users\Me\work\ThirdParty\32feet\InTheHand.BluetoothLE\Platforms\Apple\GattService.unified.cs:line 46
   at InTheHand.Bluetooth.GattService.GetCharacteristicAsync(BluetoothUuid characteristic) in C:\Users\Me\work\ThirdParty\32feet\InTheHand.BluetoothLE\GattService.cs:line 32
   at TestBLELibrary.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\Me\work\TestBLELibrary\TestBLELibrary\MainPage.xaml.cs:line 80
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at TestBLELibrary.Program.Main(String[] args) in C:\Users\Me\work\TestBLELibrary\TestBLELibrary\Platforms\iOS\Program.cs:line 13
```

Looking into `PlatformGetCharacteristic(BluetoothUuid)` shows that it calls `((CBPeripheral)Device).DiscoverCharacteristics()` and uses the value of `_service.Characteristics` immediately afterwards.  It would seem that it [should wait for a callback to `DiscoverCharacteristics()`](https://learn.microsoft.com/en-us/dotnet/api/corebluetooth.cbperipheral.discovercharacteristics?view=xamarin-ios-sdk-12#corebluetooth-cbperipheral-discovercharacteristics(corebluetooth-cbuuid()-corebluetooth-cbservice)), similar to `PlatformGetCharacteristics()`.

A possible fix might be something like (shamelessly adapted from `PlatformGetCharacteristics()`):

```
        Task<GattCharacteristic> PlatformGetCharacteristic(BluetoothUuid characteristic)
        {
            TaskCompletionSource<GattCharacteristic> tcs = new TaskCompletionSource<GattCharacteristic>();
            CBPeripheral peripheral = Device;

            void handler(object sender, CBServiceEventArgs args)
            {
#if NET6_0_OR_GREATER
                peripheral.DiscoveredCharacteristics -= handler;
#else
                peripheral.DiscoveredCharacteristic -= handler;
#endif
                if (args.Error != null)
                    tcs.SetException(new Exception(args.Error.ToString()));

                GattCharacteristic matchingCharacteristic = null;
                foreach (CBCharacteristic cbcharacteristic in _service.Characteristics)
                {
                    if ((BluetoothUuid)cbcharacteristic.UUID == characteristic)
                    {
                        matchingCharacteristic = new GattCharacteristic(this, cbcharacteristic);
                        break;
                    }
                }

                tcs.SetResult(matchingCharacteristic);
            }

#if NET6_0_OR_GREATER
            peripheral.DiscoveredCharacteristics += handler;
#else
            peripheral.DiscoveredCharacteristic += handler;
#endif
            ((CBPeripheral)Device).DiscoverCharacteristics(new CBUUID[] { characteristic }, _service);

            return tcs.Task;
        }
```

**Comment by peterfoot** [comment]
Resolved in 4.0.32
