### ISSUE TITLE
await Bluetooth.GetAvailabilityAsync() causes an exception on Windows

### ISSUE THREAD

**Issue by scottdmorgan** [inthehand/32feet#241]
After upgrading InTheHand.BluetoothLE from version 4.0.25 to 4.0.27 on Windows when running this line:

BluetoothAvailable = await Bluetooth.GetAvailabilityAsync();

I am seeing this exception:

System.Exception
  HResult=0x80040154
  Message=Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InTheHand.Bluetooth.Bluetooth.<GetRadio>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InTheHand.Bluetooth.Bluetooth.<PlatformGetAvailability>d__22.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at (my project file).<CheckBluetoothAvailability>d__20.MoveNext() in (my project file):line 85

If I comment out this line the Bluetooth library is not having any other issues. Any ideas what might be happening here?

**Comment by scottdmorgan** [comment]
Looks like my application just wasn't set to compile as 64-bit.
