### ISSUE TITLE
Discover Devicces -> Class not registered

### ISSUE THREAD

**Issue by vikramtamboli** [inthehand/32feet#279]
2023-03-11 14:35:59.747 +05:30 [ERR] Start Discovery
System.Exception: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InTheHand.Bluetooth.Bluetooth.<GetRadio>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InTheHand.Bluetooth.Bluetooth.<PlatformGetAvailability>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BlueS.Service.DiscoveryService.<StartDiscovery>d__23.MoveNext()

I have compiled my application on Win-11 anr while i run it on Win-10 gives me below exception
This same code wirked well when it was compiled on Win-10 are run on Win-10

Not sure what is the issue here 

the exception does not mention which class is not registered 

 can you help to resolve the same?

**Comment by Ylianst** [comment]
I am getting the same issue. Looking for a solution.
