### ISSUE TITLE
I have not been able to use this library to communicate with a bluetooth device (RFComm)

### ISSUE THREAD

**Issue by embeddedmz** [inthehand/32feet#332]
Hi,

This is my code (C# NET 6, VS 2022, NuGet package : InTheHand.Net.Bluetooth 4.0.36) :

```
using System;
using System.Diagnostics;
using System.IO;
using System.Net.Sockets;
using System.Text;
using InTheHand.Net;
using InTheHand.Net.Bluetooth;
using InTheHand.Net.Sockets;

using static Prevo100CSharp.Controller;

namespace Prevo100CSharp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            byte[] outBuffer = new byte[26];
            byte[] inBuffer = new byte[40];

            // Fill outBuffer with data...

            String address = "AA:BB:CC:DD:EE:FF"; // my device address
            Guid mUUID = new Guid("e0cbf06c-cd8b-4647-bb8a-263b43f0f974"); // found this on the hardware manager (my device properties), I don't know if it's correct

            BluetoothAddress addr = BluetoothAddress.Parse(address);
            BluetoothClient client = new BluetoothClient(); // <==== EXCEPTION HERE
            client.Connect(addr, mUUID); // maybe I should replace mUUID by BluetoothService.SerialPort

            var stream = client.GetStream(); 

            stream.Write(outBuffer, 0, outBuffer.Length);
            int ret = stream.Read(inBuffer, 0 , inBuffer.Length);

            Console.WriteLine("Rcvd '{0}' bytes", ret);

            stream.Close();
            client.Close();
        }
    }
}
```

I got this exception :

> System.NotImplementedException
>   HResult=0x80004001
>   Message=This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
>   Source=InTheHand.Net.Bluetooth
>   Arborescence des appels de procédure :
>    à InTheHand.Net.Sockets.BluetoothClient.PlatformInitialize() dans S:\Repos\inthehand\32feet\InTheHand.Net.Bluetooth\Platforms\Standard\BluetoothClient.standard.cs :ligne 21
>    à InTheHand.Net.Sockets.BluetoothClient..ctor() dans S:\Repos\inthehand\32feet\InTheHand.Net.Bluetooth\BluetoothClient.cs :ligne 26

ChatGPT gave me a code that is not compatible with the version of the nuget package.

I modified this sample 32feet\Samples\RfcommClientWin32\, I had to upgrade the project to .NET 4.8 (it was .NET 4.5).

and after a Write operation, the read operation throws this exception :

> System.Net.Sockets.SocketException
>   HResult=0x80004005
>   Message=Une requête d’envoi ou de réception de données n’a pas été autorisée car le socket n’est pas connecté et (lors de l’envoi sur un socket datagramme en utilisant un appel sendto) aucune adresse n’a été fournie
>   Source=System
>   Arborescence des appels de procédure :
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at InTheHand.Net.Sockets.Win32NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at RfcommClientWin32.MainWindow.<MainWindow_Activated>d__1.MoveNext() in D:\DevProjects\32feet\Samples\RfcommClientWin32\MainWindow.xaml.cs:line 127

Can you please help me ?

**Comment by embeddedmz** [comment]
Setting the target OS to Windows in the project properties fixed the System.NotImplementedException.
