### ISSUE TITLE
Bluetooth.ScanForDevicesAsync() throws 'No path specified for UNIX transport'

### ISSUE THREAD

**Issue by DevInOrbit** [inthehand/32feet#341]
Using latest Nuget package and running on Windows 10, calling Bluetooth.ScanForDevicesAsync()  results in this exception:

Tmds.DBus.ConnectException: 'No path specified for UNIX transport'

Target framework .NET 7 (tried 6 also)
Visual Studio 2022
Tried setting target OS windows 10, 8 and 7 with same results. 

Did I miss a vital configuration step or is this a valid defect. Thanks!

**Comment by msschl** [comment]
My current csproj looks like this

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.34" />
  </ItemGroup>

</Project>
```

The code like this:

```cs
// See https://aka.ms/new-console-template for more information
using InTheHand.Bluetooth;

Console.WriteLine("Hello, World!");

var discoveredDevices = await Bluetooth.ScanForDevicesAsync();
```
It fails with the following error
```sh
Unhandled exception. System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at InTheHand.Net.Sockets.BluetoothClient.PlatformInitialize()
   at InTheHand.Net.Sockets.BluetoothClient..ctor()
   at Program.<Main>$(String[] args) in W:\tmp\bluethooth\Program.cs:line 6
```

**Comment by NickRimmer** [comment]
Same issue on `Windows 11` with `.net6`

**Comment by XoBoR** [comment]
Hi, I'm having the same issue in Windows 11 with .net 8.0, changing the .net version does not help in my case as well.

Has anyone found a Solution or workaround for this?

**Comment by LLIAMAH** [comment]
+1
Win 10 .NET 8 & .NET 7

**Comment by czuryk** [comment]
I have the same problem, but I found temproary working solution.
Also I use advice from [here](https://github.com/inthehand/32feet/discussions/346#discussioncomment-7081401).
Change target framework to: **<TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>**
Set Platforms **<Platforms>x64</Platforms>**

Here is my csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.35" />
  </ItemGroup>
</Project>
```

_I use Win10, VS 2022 (17.6.2)._

Now I getting results from Bluetooth.ScanForDevicesAsync() without errors

**Comment by morgankenyon** [comment]
Similar issues, but since I'm not on .net8 and windows 11, this is my csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.36" />
  </ItemGroup>

</Project>


```

**Comment by mt09sp** [comment]
Nearly a year after this was raised...

If you want to know what to set for TargetFramework 
Have a look at the dependency for the nuget package.

Look for net7.0-windows10.0.19041 as of 4.0.36 for InTheHand.BluetoothLE

**Comment by orangeagain** [comment]
check ConsoleApp1\obj\project.assets.json to find version

**Comment by GregWoods** [comment]
This thread solved the problem for me... but for clarity, I compiled and ran my test app again the following windows versions... Here are the results.

**Target OS Version** (latest first)
10.0.26100 works  (Windows 11 24H2)
10.0.22621 works  (Windows 11 22H2)
10.0.22000 works  (Windows 11 21H2)
10.0.20348 works  (Windows Server 2022)
10.0.19041 works  (Windows 10 20H1)
10.0.18362 FAILS - (Windows 10 1903)  ERROR: No path specified for UNIX transport at Tmds.DBus.Connection.DoConnectAsync()
10.0.17763.0 Untested. I assumed it would fail

As you can see, later versions of Windows work fine.
