### ISSUE TITLE
LinuxSocket.Dispose throws if socket was not connected

### ISSUE THREAD

**Issue by ArXen42** [inthehand/32feet#407]
```cs
public static void Main(String[] args)
{
    var socket = new LinuxSocket();
    socket.Dispose();
}
```
results in:
```
Unhandled exception. System.Net.Sockets.SocketException (107): Transport endpoint is not connected
   at InTheHand.Net.Sockets.LinuxSocket.ThrowOnSocketError(Int32 result, Boolean throwOnDisconnected)
   at InTheHand.Net.Sockets.LinuxSocket.get_RemoteEndPoint()
   at InTheHand.Net.Sockets.LinuxSocket.get_Connected()
   at InTheHand.Net.Sockets.LinuxSocket.Dispose(Boolean disposing)
   at System.Net.Sockets.Socket.Dispose()
```

So far I don't see any obvious reason to not just call Close unconditionally in Dispose implementation instead of checking result of `getpeername` (called by `RemoteEndPoint` property, which then throws due to received error code).

**Comment by peterfoot** [comment]
Good catch. If the _socket value is not zero we should close anyway to release resources. I've made the change and it'll be in the next release.
