### ISSUE TITLE
Bluetooth.LE in net8.0-windows attempts to load Linux code

### ISSUE THREAD

**Issue by crener** [inthehand/32feet#411]
Hello
If I do the following code in a normal `net8.0-windows` program:

```csharp
using InTheHand.Bluetooth;

namespace ConsoleApp1
{
    internal class Program
    {
        public static Task Main(string[] args)
        { 
            IReadOnlyCollection<BluetoothDevice> devices = await Bluetooth.ScanForDevicesAsync();
        }
    }
}
```

The code inside the library seems to go into the `Bluetooth.Linux.cs` file even though my project is platform specific. 
```
Tmds.DBus.ConnectException: No path specified for UNIX transport
 ---> System.ArgumentException: No path specified for UNIX transport
   at Tmds.DBus.AddressEntry.ResolveAsync(Boolean listen)
   at Tmds.DBus.Transports.TransportSocket.ConnectUnixAsync(AddressEntry entry, CancellationToken cancellationToken, Boolean supportsFdPassing)
   at Tmds.DBus.Transports.Transport.ConnectAsync(AddressEntry entry, ClientSetupResult connectionContext, CancellationToken cancellationToken)
   at Tmds.DBus.DBusConnection.ConnectAsync(ClientSetupResult connectionContext, Boolean runContinuationsAsynchronously, Action`1 onDisconnect, CancellationToken cancellationToken)
   at Tmds.DBus.Connection.DoConnectAsync()
   --- End of inner exception stack trace ---
   at Tmds.DBus.Connection.DoConnectAsync()
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at Linux.Bluetooth.BlueZManager.GetProxiesAsync[T](String interfaceName, IDBusObject rootObject)
   at Linux.Bluetooth.BlueZManager.GetAdaptersAsync()
   at InTheHand.Bluetooth.Bluetooth.Initialize()
   at InTheHand.Bluetooth.Bluetooth.PlatformScanForDevices(RequestDeviceOptions options, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\User\RiderProjects\SonyBluetooth\ConsoleApp1\Program.cs:line 9
   at ConsoleApp1.Program.<Main>(String[] args)
```

I think this is something wrong with how the nuget package spec is determining the platform that I'm trying to use and defaulting to Linux for some reason.

I've looked around for an existing issue to this bug but didn't find one, sorry if this is a duplicate.

**Comment by crener** [comment]
After some more research I think that I'm dumb and this is down to a limitation of the Windows SDK not being referenceable.

https://aka.ms/netsdk1130 mentions that the recommended way to use any of the newer language version is to target `net5.0-windows10.0.19041.0` which this doesn't support BUT it does support (officially) but it does support `net6.0-windows10.0.19041` and `net7.0-windows10.0.19041`, so I'm just gonna use one of those versions instead.

So for someone looking at this in the future, blame MS for hiding away their own API and use the above version when trying to use Bluetooth LE with windows.
